---
# tasks file for mysql
- name: install mysql package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb

- name: copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
  notify:
    - restart mysql

- name: Start MySQL service
  service: name=mysql state=started enabled=yes

