---
# tasks file for tomcat
- name: Add repo jor java 8
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: set license selected
  shell: /bin/echo debconf shared/accepted-orcale-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: set license seen
  shell: /bin/echo debconf shared/accepted-orcale-license-v1-1 seen true | /usr/bin/debconf-set-selections

- name: install java 8
  apt: name=oracle-java8-set-default force=yes state=present update_cache=yes 
 
- name: install apache2 
  apt: name={{ item }} update_cache=yes
  with_items:
       - apache2

- name: enable mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
     - restart apache2

- name: apache2 listen on port {{ http_port }}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
  notify: 
     - restart apache2

- name: Create virtualhost file
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  args: 
     creates: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify:
     - restart apache2

   
- name: Download Tomcat 7
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.42/bin/apache-tomcat-7.0.42.tar.gz dest=/home/ubuntu/apache-tomcat-7.0.42.tar.gz

- name: Extract Tomcat
  command: chdir=/home/ubuntu tar -xzvf apache-tomcat-7.0.42.tar.gz creates=/home/ubuntu/tomcat/apache-tomcat-7.0.42

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat 
  become: yes
  become_method: sudo
  
- name: Change ownership of tomcat installation
  file: path="/home/ubuntu/apache-tomcat-7.0.42/" owner=tomcat group=tomcat state=directory recurse=yes mode=0755

- name: configure first instance
  template: src=tomcat-users.xml dest=/home/ubuntu/apache-tomcat-7.0.42/conf/
#  notify: restart tomcat

- name: create second instance
  command: cp -r /home/ubuntu/apache-tomcat-7.0.42/{{ item }} /home/ubuntu/apache-tomcat-7.0.42-instance2
  with_items:
     - "logs"
     - "temp"
     - "webapps"
     - "work"
     - "bin"
     - "conf"

- name: Update configuration for second instance in catalina.sh
  lineinfile: 
     dest: /home/ubuntu/apache-tomcat-7.0.42-instance2/bin/catalina.sh
     regexp: '^\[ -z "CATALINA_BASE"'
     line: 'CATALINA_BASE="/home/ubuntu/apache-tomcat-7.0.42-instance2"'

- name: change ownership of second instance
  file: path="/home/ubuntu/apache-tomcat-7.0.42-instance2/" owner=tomcat group=tomcat state=directory recurse=yes mode=0755

- name: change parameter for second instance in server.xml
  template: src=server.xml dest=/home/ubuntu/apache-tomcat-7.0.42-instance2/conf

- name: start tomcat
  command: /home/ubuntu/apache-tomcat-7.0.42/bin/startup.sh

- name: wait for tomcat to start
  wait_for: port=8080
  ignore_errors: yes

- name: start instance 2
  command: /home/ubuntu/apache-tomcat-7.0.42-instance2/bin/startup.sh

#- name: wait for instance 2 to start
#  command: port=8181
